OFFSET = 5
START_DATE = "2022/01/01"
months = {}
clubs = ["art-k", "badminton", "football", "swimming"]
deliveries = ["amazon", "deliveroo"]
travel = ["shell", "bp", "pump", "parkin", "uber", "ringgo", "parking"]
stores = ["sainsburys", "tesco", "superdug", "boots", "wilko", "lloyds", "butcher", "clarks", "lidl", "unismart", "waitrose"]
restaurants = ["dominos", "kfc", "costa", "cafe", "cakebox", "livingston", "restaurant"]
commodities = ["warhammer", "autocentre", "leisure", "odeon"]
WIDTH = 0.5
FONT = 7
